export const POST_FAILURE = "POST_FAILURE";
export const POST_LOADING = "POST_LOADING";
export const CREATE_POST = "CREATE_POST";
export const FETCH_POSTS = "FETCH_POSTS";
export const GET_POST_DETAILS = "GET_POST_DETAILS";
export const POST_DETAILS_LOADING = "POST_DETAILS_LOADING";
export const POST_DETAILS_FAILURE = "POST_DETAILS_FAILURE";

export const UPDATE_POST = "UPDATE_POST";
export const DELETE_POST = "DELETE_POST";

export const PAGE_FAILURE = "PAGE_FAILURE";
export const PAGE_LOADING = "PAGE_LOADING";
export const GET_PAGES = "GET_PAGES";
export const UPLOAD_PAGES = "UPLOAD_PAGES";
export const DELETE_PAGES = "DELETE_PAGES";

export const GET_TOPIC = "GET_TOPIC";
export const GET_TOPIC_LOADING = "GET_TOPIC_LOADING";
export const GET_TOPIC_FAILED = "GET_TOPIC_FAILED";

export const COMMENTS_LOADING = "COMMENTS_LOADING";
export const COMMENTS_ERROR = "COMMENTS_ERROR";
export const FETCH_COMMENTS = "FETCH_COMMENTS";
export const CREATE_COMMENT = "CREATE_COMMENT";
export const UPDATE_COMMENT = "UPDATE_COMMENT";
export const DELETE_COMMENT = "DELETE_COMMENT";

export const AUTH_FAILURE = "AUTH_FAILURE";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";

export const GET_PROFILE_DATA = "GET_PROFILE_DATA";
export const GET_PROFILE_DATA_LOADING = "GET_PROFILE_DATA_LOADING";
export const GET_PROFILE_DATA_FAILED = "GET_PROFILE_DATA_FAILED";

export const ERROR_HANDLER = "ERROR_HANDLER";
export const CLEAR_ERROR = "CLEAR_ERROR";