export const CREATE_POST = "CREATE_POST";
export const FETCH_POSTS = "FETCH_POSTS";
export const GET_POST_DETAILS = "GET_POST_DETAILS";
export const UPDATE_POST = "UPDATE_POST";
export const DELETE_POST = "DELETE_POST";

export const GET_PAGES = "GET_PAGES";
export const UPLOAD_PAGES = "UPLOAD_PAGES";
export const DELETE_PAGES = "DELETE_PAGES";

export const GET_TOPIC = "GET_TOPIC";

export const FETCH_COMMENTS = "FETCH_COMMENTS";
export const CREATE_COMMENT = "CREATE_COMMENT";
export const UPDATE_COMMENT = "UPDATE_COMMENT";
export const DELETE_COMMENT = "DELETE_COMMENT";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";
