export const CREATE_POST = "CREATE_POST";
export const CREATE_POST_LOADING = "CREATE_POST_LOADING";
export const CREATE_POST_FAILED = "CREATE_POST_FAILED";

export const FETCH_POSTS = "FETCH_POSTS";
export const FETCH_POSTS_LOADING = "FETCH_POSTS_LOADING";
export const FETCH_POSTS_FAILDED = "FETCH_POSTS_FAILDED";

export const GET_POST_DETAILS = "GET_POST_DETAILS";
export const GET_POST_DETAILS_LOADING = "GET_POST_DETAILS_LOADING";
export const GET_POST_DETAILS_FAILED = "GET_POST_DETAILS_FAILED";

export const UPDATE_POST = "UPDATE_POST";
export const UPDATE_POST_LOADING = "UPDATE_POST_LOADING";
export const UPDATE_POST_FAILED = "UPDATE_POST_FAILED";

export const DELETE_POST = "DELETE_POST";
export const DELETE_POST_LOADING = "DELETE_POST_LOADING";
export const DELETE_POST_FAILED = "DELETE_POST_FAILED";

export const GET_PAGES = "GET_PAGES";
export const GET_PAGES_LOADING = "GET_PAGES_LOADING";
export const GET_PAGES_FAILED = "GET_PAGES_FAILED";


export const UPLOAD_PAGES = "UPLOAD_PAGES";
export const UPLOAD_PAGES_LOADING = "UPLOAD_PAGES_LOADING";
export const UPLOAD_PAGES_FAILED = "UPLOAD_PAGES_FAILED";

export const DELETE_PAGES = "DELETE_PAGES";
export const DELETE_PAGES_LOADING = "DELETE_PAGES_LOADING";
export const DELETE_PAGES_FAILED = "DELETE_PAGES_FAILED";


export const GET_TOPIC = "GET_TOPIC";
export const GET_TOPIC_LOADING = "GET_TOPIC_LOADING";
export const GET_TOPIC_FAILED = "GET_TOPIC_FAILED";

export const COMMENTS_LOADING = "COMMENTS_LOADING";
export const COMMENTS_ERROR = "COMMENTS_ERROR";
export const FETCH_COMMENTS = "FETCH_COMMENTS";
export const CREATE_COMMENT = "CREATE_COMMENT";
export const UPDATE_COMMENT = "UPDATE_COMMENT";
export const DELETE_COMMENT = "DELETE_COMMENT";

export const AUTH_FAILURE = "AUTH_FAILURE";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";


export const GET_PROFILE_DATA = "GET_PROFILE_DATA";
export const GET_PROFILE_DATA_LOADING = "GET_PROFILE_DATA_LOADING";
export const GET_PROFILE_DATA_FAILED = "GET_PROFILE_DATA_FAILED";
